name: flcore
description: "A new Flutter plugin project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.6.0
  flutter: ">=3.27.0"

dependencies:
  app_settings: ^5.1.1
  device_info_plus: ^11.2.0
  dio: ^5.7.0
  encrypt: ^5.0.3
  flutter:
    sdk: flutter
  in_app_update: ^4.2.3
  intl: ^0.20.1
  meta: ^1.15.0
  package_info_plus: ^8.1.2
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  plugin_platform_interface: ^2.0.2
  share_plus: ^10.1.3
  shared_preferences: ^2.3.4
  sqflite: ^2.4.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.fl.flcore
        pluginClass: FlcorePlugin
      ios:
        pluginClass: FlcorePlugin
